dataFile <- "./exdata_data_household_power_consumption/household_power_consumption.txt"
data <- read.delim(dataFile, header=TRUE, sep=";", na.strings = "?")
data1 <- subset(data, data$Date=="1/2/2007" | data$Date== "2/2/2007")
data1$Time <- strptime(paste(data1$Date, data1$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(x=data1$Time, y=data1$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(x=data1$Time, y=data1$Sub_metering_2, col="red")
lines(x=data1$Time, y=data1$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1,col=c("black", "red", "blue"))
dev.off()